name: master

on:
 workflow_dispatch:

jobs:

  master:

    runs-on: ubuntu-20.04
    timeout-minutes: 9999

    steps:

    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@v1.2.0
      with:
        tool-cache: true

    - name: Download Script.
      run: sudo wget http://raw.githubusercontent.com/CE1CECL/n/main/master
    - name: Chmod Script
      run: sudo chmod 7777 -vR ./master
    - name: Run Script
      run: sudo ./master
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
         name: master.tar.zst
         path: /home/runner/master.tar.zst
