name: master

on:
 workflow_dispatch:

jobs:

  a:

    runs-on: ubuntu-20.04
    timeout-minutes: 9999

    steps:

    - name: Download Script.
      run: sudo wget http://raw.githubusercontent.com/CE1CECL/n/main/master
    - name: Chmod Script
      run: sudo chmod 777 -R ./master
    - name: Run Script
      run: sudo ./master
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
         name: m.tar.zst
         path: /home/runner/m.tar.zst
