name: pb

on:
 workflow_dispatch:

jobs:

  a:

    runs-on: ubuntu-20.04
    timeout-minutes: 9999

    steps:

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.2.0
      with:
        tool-cache: true

    - name: Download Script.
      run: sudo wget http://raw.githubusercontent.com/CE1CECL/n/main/pb
    - name: Chmod Script
      run: sudo chmod 7777 -vR ./pb
    - name: Run Script
      run: sudo ./pb
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
         name: pb.tar.zst
         path: /home/runner/pb.tar.zst
